---
title: 'Reproducing Real Science Progess Report 2: Bowen et al. 2017'
output:
  html_document:
    df_print: paged
---

To this point I have downloaded all the data and scripts from github and have ran through all of the "Function parsing and correlations" which broke down the data and created correlation maps of different biological processes and how they affect other biological processes.  These again are unrelated to the final SEM model I am interested in.

## The problem

The main problem I had last week was that all the previous scripts leading up the the SEM model were running perfectly, but when it came to the SEM model there was an error that popped up.  The error read: 

Error in sem.fit(sem_mod_nlme, data = exp_data_func, corr.errors = c("belowbiomass_g~~abovebiomass_g",  : 
  could not find function "sem.fit"
  
It seems as though the sem.fit function has since been replaced by a new function or somehow the syntax of the new version may be different.  Looking back to when the author originally used the "piecewiseSEM" package they were likely using version 1.x, and the current package my system has loaded in verion 2.1.0. 

To find how the "piecewiseSEM" package has changed from verion 1.x to 2.1.0 I looked up "piecewiseSEM" on google to find a page from "The Comprehensize R Archive Network" (https://cran.r-project.org/web/packages/piecewiseSEM/vignettes/piecewiseSEM.html) which describes how to use the "piecewiseSEM" package.  

In section 3.2 "Comparing versions in evaluating the Shipley’s SEM" the author describes that the old version of the package the model was run off of a constructed "list" of linear models.  For example from bowen et al. 2017:

  gen_div_status <- lme(observed_otus~  status, 
                      random =~ 1|Genotype, data=exp_data_func, method="ML")
  gen_activity_status <- lme(rd ~ status + observed_otus, 
                           random =~ 1|Genotype, data=exp_data_func, method="ML")
  gen_meta_status <- lme(`Metabolism`~ status+ observed_otus, 
                       random =~ 1|Genotype, data=exp_data_func, method="ML")
  phen_mod_status <- lme(belowgallic_uM ~ rd + observed_otus + Metabolism + status, 
                       random =~ 1|Genotype, data=exp_data_func, method="ML")
  c_mod_status <- lme(belowC ~ rd + observed_otus + Metabolism + status + belowgallic_uM     +
                      belowbiomass_g + abovebiomass_g, 
                    random =~ 1|Genotype, data=exp_data_func, method="ML")
  n_mod_status <- lme(belowN ~ rd + observed_otus + Metabolism + status +
                      belowbiomass_g + abovebiomass_g, 
                    random =~ 1|Genotype, data=exp_data_func, method="ML")

  biomass_mod_status <- lme(belowbiomass_g ~ rd + belowgallic_uM +  
                            observed_otus + Metabolism + status, 
                          random =~ 1|Genotype, data=exp_data_func, method="ML")
  Abiomass_mod_status <- lme(abovebiomass_g ~ rd + belowgallic_uM + 
                             observed_otus + Metabolism + status, 
                           random =~ 1|Genotype, data=exp_data_func, method="ML")

  sem_mod_nlme <- list(
    gen_div_status,
    gen_activity_status,
    gen_meta_status,
    phen_mod_status,
    c_mod_status,
    n_mod_status,
    biomass_mod_status,
    Abiomass_mod_status
  
    )
    
This created a list of all the linear models fed into the SEM model called "sem_mod_nmle". 

## Solving the problem from last week

The new version of the the package omits the list and uses the "psem" function which converts the list into this "psem" object.  So I edited the chunk of code seed above to this new one:

  bowen.psem<-psem(lme(observed_otus~  status, 
                                       random =~ 1|Genotype, data=exp_data_func, method="ML"),
                 lme(rd ~ status + observed_otus, 
                                            random =~ 1|Genotype, data=exp_data_func, method="ML"),
                 lme(`Metabolism`~ status+ observed_otus, 
                                        random =~ 1|Genotype, data=exp_data_func, method="ML"),
                 lme(belowgallic_uM ~ rd + observed_otus + Metabolism + status, 
                                        random =~ 1|Genotype, data=exp_data_func, method="ML"),
                 lme(belowC ~ rd + observed_otus + Metabolism + status + belowgallic_uM +
                                       belowbiomass_g + abovebiomass_g, 
                                     random =~ 1|Genotype, data=exp_data_func, method="ML"),
                 lme(belowN ~ rd + observed_otus + Metabolism + status +
                                       belowbiomass_g + abovebiomass_g, 
                                     random =~ 1|Genotype, data=exp_data_func, method="ML"),
                 lme(belowbiomass_g ~ rd + belowgallic_uM +  
                                             observed_otus + Metabolism + status, 
                                           random =~ 1|Genotype, data=exp_data_func, method="ML"),
                 lme(abovebiomass_g ~ rd + belowgallic_uM + 
                                              observed_otus + Metabolism + status, 
                                            random =~ 1|Genotype, data=exp_data_func, method="ML"))

  (sem_mod_nlme <- summary(bowen.psem, .progressBar = F))
  
This summary gave me the SEM fit information":

Structural Equation Model of bowen.psem 

Call:
  observed_otus ~ status
  rd ~ status + observed_otus
  Metabolism ~ status + observed_otus
  belowgallic_uM ~ rd + observed_otus + Metabolism + status
  belowC ~ rd + observed_otus + Metabolism + status + belowgallic_uM + belowbiomass_g + abovebiomass_g
  belowN ~ rd + observed_otus + Metabolism + status + belowbiomass_g + abovebiomass_g
  belowbiomass_g ~ rd + belowgallic_uM + observed_otus + Metabolism + status
  abovebiomass_g ~ rd + belowgallic_uM + observed_otus + Metabolism + status

    AIC      BIC
 171.238   318.698

---
Tests of directed separation:

                         Independ.Claim Test.Type DF Crit.Value P.Value    
                  Metabolism ~ rd + ...      coef 57     1.6826  0.0979    
          belowN ~ belowgallic_uM + ...      coef 53     0.2346  0.8154    
                  belowN ~ belowC + ...      coef 52    -2.7636  0.0079  **
  abovebiomass_g ~ belowbiomass_g + ...      coef 54     5.6365  0.0000 ***

Global goodness-of-fit:

  Fisher's C = 43.238 with P-value = 0 and on 8 degrees of freedom

---
Coefficients:

        Response           Predictor     Estimate  Std.Error DF Crit.Value P.Value
   observed_otus              status            -          -  2     5.9969  0.0499
   observed_otus status = introduced    2533.8853   126.0395 14    20.1039  0.0000
   observed_otus   status = invasive    2530.0265    53.7327 12    47.0854  0.0000
   observed_otus     status = native    2259.9211   101.4606 12    22.2739  0.0000
              rd       observed_otus            0          0 58     1.8264  0.0729
              rd              status            -          -  2     9.0062  0.0111
              rd status = introduced       0.7306     0.0263 14    27.8007  0.0000
              rd   status = invasive        0.712     0.0117 12    60.8366  0.0000
              rd     status = native       0.7835     0.0215 12    36.4189  0.0000
      Metabolism       observed_otus      -7.1471     7.0558 58    -1.0129  0.3153
      Metabolism              status            -          -  2    25.4982  0.0000
      Metabolism status = introduced    3174705.7 21047.6451 14   150.8342  0.0000
      Metabolism   status = invasive 3072964.4313  9371.6314 12   327.9007  0.0000
      Metabolism     status = native 3131122.4927 17231.5449 12   181.7088  0.0000
  belowgallic_uM                  rd    -162.7788   644.8918 56    -0.2524  0.8016
  belowgallic_uM       observed_otus       0.0485     0.0818 56     0.5920  0.5562
  belowgallic_uM          Metabolism        8e-04      8e-04 56     1.0150  0.3145
  belowgallic_uM              status            -          -  2     2.9950  0.2237
  belowgallic_uM status = introduced     372.0259    97.1737 14     3.8285  0.0018
  belowgallic_uM   status = invasive     436.0405    37.0284 12    11.7759  0.0000
  belowgallic_uM     status = native     545.6028    75.1155 12     7.2635  0.0000
          belowC                  rd      -0.2783      2.685 53    -0.1036  0.9178
          belowC       observed_otus        7e-04      3e-04 53     2.1134  0.0393
          belowC          Metabolism            0          0 53    -1.2533  0.2156
          belowC      belowgallic_uM       0.0014      5e-04 53     2.7154  0.0089
          belowC      belowbiomass_g      -0.1882     0.1587 53    -1.1864  0.2408
          belowC      abovebiomass_g       0.1053     0.2276 53     0.4626  0.6456
          belowC              status            -          -  2    13.5056  0.0012
          belowC status = introduced      42.7692     0.5135 14    83.2893  0.0000
          belowC   status = invasive      43.4143     0.1683 12   258.0072  0.0000
          belowC     status = native      44.3959     0.3232 12   137.3653  0.0000
          belowN                  rd      -0.0378     1.4647 54    -0.0258  0.9795
          belowN       observed_otus       -2e-04      2e-04 54    -1.3579  0.1801
          belowN          Metabolism            0          0 54    -0.4609  0.6467
          belowN      belowbiomass_g      -0.0801     0.0765 54    -1.0465  0.3000
          belowN      abovebiomass_g      -0.0919     0.1064 54    -0.8644  0.3912
          belowN              status            -          -  2     2.1292  0.3449
          belowN status = introduced       1.4373     0.2686 14     5.3501  0.0001
          belowN   status = invasive       1.1725     0.0943 12    12.4351  0.0000
          belowN     status = native       1.0433     0.1792 12     5.8232  0.0001
  belowbiomass_g                  rd      -2.5988     3.0193 55    -0.8607  0.3931
  belowbiomass_g      belowgallic_uM       -2e-04      4e-04 55    -0.5480  0.5859
  belowbiomass_g       observed_otus       -1e-04      3e-04 55    -0.4687  0.6412
  belowbiomass_g          Metabolism            0          0 55     0.5723  0.5695
  belowbiomass_g              status            -          -  2     7.1790  0.0276
  belowbiomass_g status = introduced       0.8933     0.4896 14     1.8247  0.0895
  belowbiomass_g   status = invasive       2.1894      0.193 12    11.3450  0.0000
  belowbiomass_g     status = native       1.2979     0.3796 12     3.4193  0.0051
  abovebiomass_g                  rd      -1.3509     1.9109 55    -0.7069  0.4826
  abovebiomass_g      belowgallic_uM        1e-04      3e-04 55     0.3782  0.7067
  abovebiomass_g       observed_otus       -2e-04      2e-04 55    -0.8857  0.3796
  abovebiomass_g          Metabolism            0          0 55    -0.9800  0.3314
  abovebiomass_g              status            -          -  2    11.5158  0.0032
  abovebiomass_g status = introduced       2.8398     0.2942 14     9.6532  0.0000
  abovebiomass_g   status = invasive       1.8504     0.1132 12    16.3482  0.0000
  abovebiomass_g     status = native       1.8076     0.2282 12     7.9208  0.0000
  Std.Estimate    
             -   *
             - ***
             - ***
             - ***
             -    
             -   *
             - ***
             - ***
             - ***
             -    
             - ***
             - ***
             - ***
             - ***
       -0.0367    
        0.0774    
        0.1821    
             -    
             -  **
             - ***
             - ***
       -0.0128    
        0.2372   *
       -0.1974    
             -  **
      -38.5917    
        0.0942    
             -  **
             - ***
             - ***
             - ***
       -0.0043    
        -0.173    
       -0.0952    
             -    
       -0.2006    
             -    
             - ***
             - ***
             - ***
       -0.1341    
       -0.0552    
       -0.0507    
        0.1108    
             -   *
             -    
             - ***
             -  **
        -0.104    
        0.0421    
       -0.1063    
       -0.1796    
             -  **
             - ***
             - ***
             - ***

  Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05

---
Individual R-squared:

        Response method Marginal Conditional
   observed_otus   none     0.09        0.15
              rd   none     0.30        0.81
      Metabolism   none     0.57        0.88
  belowgallic_uM   none     0.07        0.08
          belowC   none     0.36        0.36
          belowN   none     0.10        0.21
  belowbiomass_g   none     0.27        0.45
  abovebiomass_g   none     0.21        0.27

##Getting the coefficients from the fit model

The "sem.coefs" function used by Bowen et al. 2017 was also out of date so I checked the CRAN page to see what the new procedure was.  The new function is simply "coefs" and you plug your "psem" object right into it.  So I ran coefs(bowen.psem) and got:

 Response           Predictor     Estimate  Std.Error DF Crit.Value P.Value Std.Estimate    
1   observed_otus              status            -          -  2     5.9969  0.0499            -   *
2   observed_otus status = introduced    2533.8853   126.0395 14    20.1039  0.0000            - ***
3   observed_otus   status = invasive    2530.0265    53.7327 12    47.0854  0.0000            - ***
4   observed_otus     status = native    2259.9211   101.4606 12    22.2739  0.0000            - ***
5              rd       observed_otus            0          0 58     1.8264  0.0729            -    
6              rd              status            -          -  2     9.0062  0.0111            -   *
7              rd status = introduced       0.7306     0.0263 14    27.8007  0.0000            - ***
8              rd   status = invasive        0.712     0.0117 12    60.8366  0.0000            - ***
9              rd     status = native       0.7835     0.0215 12    36.4189  0.0000            - ***
10     Metabolism       observed_otus      -7.1471     7.0558 58    -1.0129  0.3153            -    
11     Metabolism              status            -          -  2    25.4982  0.0000            - ***
12     Metabolism status = introduced    3174705.7 21047.6451 14   150.8342  0.0000            - ***
13     Metabolism   status = invasive 3072964.4313  9371.6314 12   327.9007  0.0000            - ***
14     Metabolism     status = native 3131122.4927 17231.5449 12   181.7088  0.0000            - ***
15 belowgallic_uM                  rd    -162.7788   644.8918 56    -0.2524  0.8016      -0.0367    
16 belowgallic_uM       observed_otus       0.0485     0.0818 56     0.5920  0.5562       0.0774    
17 belowgallic_uM          Metabolism        8e-04      8e-04 56     1.0150  0.3145       0.1821    
18 belowgallic_uM              status            -          -  2     2.9950  0.2237            -    
19 belowgallic_uM status = introduced     372.0259    97.1737 14     3.8285  0.0018            -  **
20 belowgallic_uM   status = invasive     436.0405    37.0284 12    11.7759  0.0000            - ***
21 belowgallic_uM     status = native     545.6028    75.1155 12     7.2635  0.0000            - ***
22         belowC                  rd      -0.2783      2.685 53    -0.1036  0.9178      -0.0128    
23         belowC       observed_otus        7e-04      3e-04 53     2.1134  0.0393       0.2372   *
24         belowC          Metabolism            0          0 53    -1.2533  0.2156      -0.1974    
25         belowC      belowgallic_uM       0.0014      5e-04 53     2.7154  0.0089            -  **
26         belowC      belowbiomass_g      -0.1882     0.1587 53    -1.1864  0.2408     -38.5917    
27         belowC      abovebiomass_g       0.1053     0.2276 53     0.4626  0.6456       0.0942    
28         belowC              status            -          -  2    13.5056  0.0012            -  **
29         belowC status = introduced      42.7692     0.5135 14    83.2893  0.0000            - ***
30         belowC   status = invasive      43.4143     0.1683 12   258.0072  0.0000            - ***
31         belowC     status = native      44.3959     0.3232 12   137.3653  0.0000            - ***
32         belowN                  rd      -0.0378     1.4647 54    -0.0258  0.9795      -0.0043    
33         belowN       observed_otus       -2e-04      2e-04 54    -1.3579  0.1801       -0.173    
34         belowN          Metabolism            0          0 54    -0.4609  0.6467      -0.0952    
35         belowN      belowbiomass_g      -0.0801     0.0765 54    -1.0465  0.3000            -    
36         belowN      abovebiomass_g      -0.0919     0.1064 54    -0.8644  0.3912      -0.2006    
37         belowN              status            -          -  2     2.1292  0.3449            -    
38         belowN status = introduced       1.4373     0.2686 14     5.3501  0.0001            - ***
39         belowN   status = invasive       1.1725     0.0943 12    12.4351  0.0000            - ***
40         belowN     status = native       1.0433     0.1792 12     5.8232  0.0001            - ***
41 belowbiomass_g                  rd      -2.5988     3.0193 55    -0.8607  0.3931      -0.1341    
42 belowbiomass_g      belowgallic_uM       -2e-04      4e-04 55    -0.5480  0.5859      -0.0552    
43 belowbiomass_g       observed_otus       -1e-04      3e-04 55    -0.4687  0.6412      -0.0507    
44 belowbiomass_g          Metabolism            0          0 55     0.5723  0.5695       0.1108    
45 belowbiomass_g              status            -          -  2     7.1790  0.0276            -   *
46 belowbiomass_g status = introduced       0.8933     0.4896 14     1.8247  0.0895            -    
47 belowbiomass_g   status = invasive       2.1894      0.193 12    11.3450  0.0000            - ***
48 belowbiomass_g     status = native       1.2979     0.3796 12     3.4193  0.0051            -  **
49 abovebiomass_g                  rd      -1.3509     1.9109 55    -0.7069  0.4826       -0.104    
50 abovebiomass_g      belowgallic_uM        1e-04      3e-04 55     0.3782  0.7067       0.0421    
51 abovebiomass_g       observed_otus       -2e-04      2e-04 55    -0.8857  0.3796      -0.1063    
52 abovebiomass_g          Metabolism            0          0 55    -0.9800  0.3314      -0.1796    
53 abovebiomass_g              status            -          -  2    11.5158  0.0032            -  **
54 abovebiomass_g status = introduced       2.8398     0.2942 14     9.6532  0.0000            - ***
55 abovebiomass_g   status = invasive       1.8504     0.1132 12    16.3482  0.0000            - ***
56 abovebiomass_g     status = native       1.8076     0.2282 12     7.9208  0.0000            - ***
There were 17 warnings (use warnings() to see them)

## Where I am now

   There are correlation errors inputed into each of the sem.fit and sem.coef functions the author wrote, I did not integrate those into the new fit model or the coefficients I ran, how does that affect my model and how can I address that?
